### ISSUE TITLE
fix: Conflicting configuration options using while using Yarn v3

### ISSUE THREAD

**Issue by RobbyUitbeijerse** [Synthetixio/docker-node#58]
Hi there!

We are running into an issue while using a docker-e2e image that is probably caused by the docker-node image it's based upon. We use yarn (v3) within our project and are running our test automation in an Azure pipeline.

While using Yarn v3 in the pipeline, we were getting the following:

`Usage Error: Unrecognized or legacy configuration settings found: production - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)`

In yarn, this means the process crashes and our test automation pipeline throws. In order to mitigate it, I tried switching to `npm` solely for our cypress pipeline, which resulted in the following warning (since it's a warning, at least our pipeline isn't crashing)

`npm WARN config production`

this felt odd to me as we didn't actually manage any npm/yarn config file until I realised that these settings seem to get set within the base Dockerfile, specifically here:

https://github.com/Synthetixio/docker-node/blob/master/output/ubuntu/18.8/Dockerfile#L17

We currently weren't able to actually find a solution which would allow us to run our pipeline. Yarn 3 is preferred, as the cypress solution is managed in a monorepo where the lockfile currently is generated by Yarn v3.

How would you feel about moving platform specific logic like this into a similar setup as the rest of the settings?

```
{%- if platform === "heroku" %}
ENV NPM_CONFIG_PRODUCTION ...
```

Lmk! Happy to apply a fix like that in a PR

**Comment by mp-dthr** [comment]
Faced the same issue.
@drptbl Can you please check this one?

**Comment by drptbl** [comment]
@RobbyUitbeijerse @mp-dthr fixed.

**Comment by RobbyUitbeijerse** [comment]
very cool @drptbl , thanks a ton. Just successfully switched to the `synthetixio/docker-e2e:18.12-ubuntu` image and yarn berry and that works without any issue now
